image: "registry.git.grepit.se/embedded-rust/atsamx7x-hal"

stages:
  - HAL
  - examples
  - lint
  - docs

default:
  before_script:
    - rustup show
    - export CARGO_TARGET_DIR="$(pwd)/target"
    - echo "$CARGO_TARGET_DIR"
    - mkdir -p cargo-home
    - export CARGO_HOME="$(pwd)/cargo-home"
    - echo "$CARGO_HOME"
  cache:
    key: "$CI_PROJECT_PATH_SLUG"
    paths:
      - target/
      - cargo-home/bin/
      - cargo-home/registry/index/
      - cargo-home/registry/cache/
      - cargo-home/git/db/

samv71q21b:
  stage: HAL
  script:
    - cd hal
    - cargo check --features samv71q21b,unproven

same70n21b:
  stage: HAL
  script:
    - cd hal
    - cargo check --features same70n21b,unproven

same70j21b:
  stage: HAL
  script:
    - cd hal
    - cargo check --features same70j21b,unproven

e70:
  stage: examples
  script:
    - cd boards/atsame70_xpro
    - cargo check --examples

v71:
  stage: examples
  script:
    - cd boards/atsamv71_xult
    - cargo check --examples

fmt:
  stage: lint
  needs: []
  script:
    - cd hal
    - cargo fmt -- --check
    - cd ../boards/atsame70_xpro
    - cargo fmt -- --check
    - cd ../atsamv71_xult
    - cargo fmt -- --check

clippy:
  stage: lint
  allow_failure: true
  needs: ["samv71q21b"]
  script:
    - cd hal
    - cargo clippy --no-deps --features samv71q21b,unproven
    - cd ../boards/atsame70_xpro
    - cargo clippy --examples --no-deps
    - cd ../atsamv71_xult
    - cargo clippy --examples --no-deps

docs:
  stage: docs
  needs: ["samv71q21b"]
  script:
    - cd hal
    - cargo doc --features samv71q21b,unproven --no-deps

doc tests:
  stage: docs
  needs: ["samv71q21b"]
  script:
    - cd hal
    - cargo test --doc --features samv71q21b,unproven --target x86_64-unknown-linux-gnu
